name: pocket-js-server

services:
  pg: 
    image: bitnami/postgresql:13.16.0
    ports:
       - '5432:5432'
    environment:
      - POSTGRES_USER=in_orbit_user
      - POSTGRES_PASSWORD=ExBuWjFlZ39ND360qmHc
      - POSTGRES_DB=in_orbit

  